---
# tasks file for ansible-java

- name: Install GPG
  apt: name=gpg state=present

- name: Add Java Repository Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EEA14886
    state: present

- name: Add Java Repository (Debian Stretch)
  apt_repository:
    repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
    state: present
    filename: java
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'

- name: Accept Java 8 License
  become: true
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java 8
  apt:
    name: "{{packages}}"
    state: present
  vars:
    packages:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
